core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('travel.urls')),
    path('auth/', include('autenticacao.urls')),
]

travel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Outras rotas...
    path('create_planet/', views.create_planet, name='create_planet'),
    path('list_planets/', views.list_planets, name='list_planets'),
    path('list_distances/', views.list_distances, name='list_distances'),
    path('create_distance/', views.create_distance, name='create_distance'),
    path('create_travel/', views.create_travel, name='create_travel'),
    path('travel/<int:travel_id>/', views.detail_travel, name='detail_travel'),
    path('', views.search_trips, name='search_trips'),
    path('search_earth_trips/', views.search_earth_trips, name='search_earth_trips'),
    path('planet/<int:pk>/', views.detail_planet, name='detail_planet'),
]

travel/models.py
from django.db import models
from datetime import datetime

class Planet(models.Model):
    name = models.CharField(max_length=100)
    diametro_km = models.FloatField()
    massa_kg = models.CharField(max_length=50)
    distancia_media_ao_sol_km = models.CharField(max_length=50)
    periodo_orbital_dias = models.CharField(max_length=50)
    temperatura_media_celsius = models.CharField(max_length=50)
    descricao = models.TextField()

    def __str__(self):
        return self.name
    
class DistanciaEntrePlanetas(models.Model):
    planeta_origem = models.ForeignKey(Planet, on_delete=models.CASCADE, related_name='distancias_partida')
    planeta_destino = models.ForeignKey(Planet, on_delete=models.CASCADE, related_name='distancias_destino')
    distancia_km = models.FloatField()
    tarifa = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f'Distância entre {self.planeta_origem.name} e {self.planeta_destino.name}'
    
class Travel(models.Model):
    departure = models.ForeignKey(Planet, on_delete=models.DO_NOTHING, related_name='trips_of_departure')
    arriving = models.ForeignKey(Planet, on_delete=models.DO_NOTHING, related_name='trips_of_arriving')
    data = models.DateField()
    time = models.TimeField()
    itinerary = models.TextField(blank=True, null=True)
    places_to_visit = models.TextField(blank=True, null=True)
    recommendations = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return f'Travel departure {self.departure} for {self.arriving} a {self.data} the {self.time}'

def search_travel(departure, arriving, data):
    data_formatada = datetime.strptime(data, '%Y-%m-%d').date()
    trips = Travel.objects.filter(departure=departure, arriving=arriving, data=data_formatada)
    return trips

travel/forms.py
from django import forms
from .models import Planet, DistanciaEntrePlanetas, Travel

class PlanetForm(forms.ModelForm):
    class Meta:
        model = Planet
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

class DistanciaForm(forms.ModelForm):
    class Meta:
        model = DistanciaEntrePlanetas
        fields = '__all__'

class TravelForm(forms.ModelForm):
    class Meta:
        model = Travel
        fields = ['departure', 'arriving', 'data', 'time']

        widgets = {
            'data': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
        }

class PesquisaViagemForm(forms.Form):
    departure = forms.ModelChoiceField(queryset=Planet.objects.all(), label='Planeta de Origem')
    arriving = forms.ModelChoiceField(queryset=Planet.objects.all(), label='Planeta de Destino')
    data = forms.DateField(label='Data da Viagem')

travel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PlanetForm, DistanciaForm, PesquisaViagemForm, TravelForm
from .models import Planet, DistanciaEntrePlanetas, Travel
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def create_planet(request):
    if request.method == 'POST':
        form = PlanetForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('list_planets')
    else:
        form = PlanetForm()

    return render(request, 'create_planets.html', {'form': form})

@csrf_exempt
def list_planets(request):
    planets = Planet.objects.all()
    return render(request, 'list_planets.html', {'planets': planets})

@csrf_exempt
def detail_planet(request, pk):
    planeta = get_object_or_404(Planet, pk=pk)

    return render(request, 'detail_planet.html', {'planeta': planeta})

@csrf_exempt
def list_distances(request):
    distances = DistanciaEntrePlanetas.objects.all()

    paginator_list_distances = Paginator(distances, 12)
    page_list_distances = request.GET.get('page')

    distances = paginator_list_distances.get_page(page_list_distances)

    return render(request, 'list_distance.html', {'distances': distances})

@csrf_exempt
def create_distance(request):
    if request.method == 'POST':
        form = DistanciaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('list_distances')
    else:
        form = DistanciaForm()

    return render(request, 'create_distance.html', {'form': form})

@csrf_exempt
def create_travel(request):
    if request.method == 'POST':
        form = TravelForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = TravelForm()

    return render(request, 'create_travel.html', {'form': form})

@csrf_exempt
def detail_travel(request, travel_id):
    viagem = get_object_or_404(Travel, id=travel_id)
    return render(request, 'detail_travel.html', {'viagem': viagem})

@csrf_exempt
def search_trips(request):
    if request.method == 'POST':
        
        departure_id = request.POST.get('departure')
        arriving_id = request.POST.get('arriving')
        data = request.POST.get('data')

        viagens = Travel.objects.filter(departure_id=departure_id, arriving_id=arriving_id, data=data)
        
        return render(request, 'results_search.html', {'viagens': viagens})

    else:
        form = PesquisaViagemForm()

    return render(request, 'search_trips.html', {'form': form})

@csrf_exempt
def search_earth_trips(request):

    departure_earth_id = 3

    viagens = Travel.objects.filter(departure_id=departure_earth_id)
    
    return render(request, 'search_departure.html', {'viagens': viagens})

travel/templates/create_distance.html
{% extends "base.html" %}
{% block 'title' %}Insert Planets{% endblock %}

{% block 'body' %}
<h1>Criar Nova Distância Entre Planetas</h1>
<hr>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="{% url 'list_distances' %}" class="btn btn-secondary">Voltar para a Lista</a>
</form>
{% endblock %}

travel/templates/create_planets.html
{% extends "base.html" %}
{% block 'title' %}Insert Planets{% endblock %}

{% block 'body' %}
<h1>Insert a New Planet</h1>
<hr>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
    <a class="btn btn-secondary" href="{% url 'list_planets' %}">Return to List of Planets</a>
</form>

{% endblock %}

travel/templates/create_travel.html
{% extends "base.html" %}
{% block 'title' %}Insert Planets{% endblock %}

{% block 'body' %}
<h1>Criar Nova Viagem Entre Planetas</h1>
<hr>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Salvar</button>
</form>

{% endblock %}

travel/templates/detail_planet.html
{% extends "base.html" %}

{% block 'title' %}Planet Details: {{ planeta.name }}{% endblock %}

{% block 'body' %}
<div class="my-3 p-3 bg-body rounded shadow-sm">
<h1>Planet Details: {{ planeta.name }}</h1>
<hr>

<p><strong>Nome:</strong> {{ planeta.name }}</p>
<p><strong>Diâmetro (km):</strong> {{ planeta.diametro_km }}</p>
<p><strong>Massa (kg):</strong> {{ planeta.massa_kg }}</p>
<p><strong>Distância Média ao Sol (km):</strong> {{ planeta.distancia_media_ao_sol_km }}</p>
<p><strong>Período Orbital (dias):</strong> {{ planeta.periodo_orbital_dias }}</p>
<p><strong>Temperatura Média (°C):</strong> {{ planeta.temperatura_media_celsius }}</p>
<p><strong>Descrição:</strong> {{ planeta.descricao }}</p>
<hr>
<a class="btn btn-secondary" href="{% url 'list_planets' %}">Return to Planets list</a>
</div>
{% endblock %}

travel/templates/detail_travel.html
{% extends "baselogin.html" %}
{% load static %}
{% block 'title' %}
    Details of Travel
{% endblock %}
{% block 'head' %}
    <link rel="stylesheet" href="{% static './css/cadastro.css' %}">
{% endblock %}
{% block 'body' %}
<div class="col-md-9">
<div class="area_cadastrar">
<div class="my-3 p-3 bg-body rounded shadow-sm">
    <h1>Travel Details</h1>
    <hr>

    <h3>Departure: {{ viagem.departure }}</h3>
    <h3>Arriving: {{ viagem.arriving }}</h3>
    <h3>Date: {{ viagem.data }}</h3>
    <h3>Time: {{ viagem.time }}</h3>

    <h2>Itinerary</h2>
    <p>{{ viagem.itinerary }}</p>

    <h2>Places to Visit</h2>
    <p>{{ viagem.places_to_visit }}</p>

    <h2>Recommendations</h2>
    <p>{{ viagem.recommendations }}</p>

    <a class="btn btn-primary" href="{% url 'search_trips' %}">Back to Travels List</a>
</div>
</div>
</div>
{% endblock %}

travel/templates/list_distance.html
{% extends "base.html" %}
{% block 'title' %}List Itineraries{% endblock %}

{% block 'body' %}
<h1>List of Itineraries</h1>
<hr>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Planeta de Origem</th>
            <th>Planeta de Destino</th>
            <th>Distância (km)</th>
            <th>Tarifa $</th>
        </tr>
    </thead>
    <tbody>
        {% for distance in distances %}
            <tr>
                <td>{{ distance.planeta_origem.name }}</td>
                <td>{{ distance.planeta_destino.name }}</td>
                <td>{{ distance.distancia_km }}</td>
                <td>{{ distance.tarifa }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">Nenhuma distância cadastrada.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<hr>
<nav aria-label="...">
  <ul class="pagination">
    {% if distances.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">Primeira</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ distances.previous_page_number }}">Anterior</a>
      </li>
    {% endif %}
    
    <li class="page-item active" aria-current="page">
      <span class="page-link">{{ distances.number }}</span>
    </li>
    
    {% if distances.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ distances.next_page_number }}">Próxima</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ distances.paginator.num_pages }}">Última</a>
      </li>
    {% endif %}
  </ul>
</nav>
<hr>
<a href="{% url 'create_distance' %}" class="btn btn-success">Insert a New Itinerarie</a>
{% endblock %}

travel/templates/list_planets.html
{% extends "base.html" %}
{% block 'title' %}List Planets{% endblock %}

{% block 'body' %}
<div class="my-3 p-3 bg-body rounded shadow-sm">
<h1>List of Planets</h1>
<hr>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Nome do Planeta</th>
            <th>Diametro em KM</th>
            <th>Massa</th>
            <th>Distancia do Sol</th>
            <th>Periodo Orbital</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for planet in planets %}
            <tr>
                <td>{{ planet.name }}</td>
                <td>{{ planet.diametro_km }}</td>
                <td>{{ planet.massa_kg }}</td>
                <td>{{ planet.distancia_media_ao_sol_km }}</td>
                <td>{{ planet.periodo_orbital_dias }}</td>
                <td><a href="{% url 'detail_planet' planet.id %}"><span class="badge text-bg-primary">Detalhes</span><a/></td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="1">Nenhum planeta encontrado.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'search_trips' %}" class="btn btn-success">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
    </svg>
    Travel between Planets
</a>
<a href="{% url 'search_earth_trips' %}" class="btn btn-secondary">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
    </svg>
    Travel Earth Departure
</a>
</div>
{% endblock %}

travel/templates/results_search.html
{% extends "baselogin.html" %}
{% block 'title' %}Available Trips{% endblock %}

{% block 'body' %}
<div class="my-3 p-3 bg-body rounded shadow-sm">
<h1>Available Trips in between Planets</h1>
<hr>

{% if viagens %}
<table class="table table-hover">
    <thead>
    <tr>
        <th>Cod</th>
        <th>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-rocket-takeoff" viewBox="0 0 16 16">
                <path d="M9.752 6.193c.599.6 1.73.437 2.528-.362.798-.799.96-1.932.362-2.531-.599-.6-1.73-.438-2.528.361-.798.8-.96 1.933-.362 2.532Z"/>
                <path d="M15.811 3.312c-.363 1.534-1.334 3.626-3.64 6.218l-.24 2.408a2.56 2.56 0 0 1-.732 1.526L8.817 15.85a.51.51 0 0 1-.867-.434l.27-1.899c.04-.28-.013-.593-.131-.956a9.42 9.42 0 0 0-.249-.657l-.082-.202c-.815-.197-1.578-.662-2.191-1.277-.614-.615-1.079-1.379-1.275-2.195l-.203-.083a9.556 9.556 0 0 0-.655-.248c-.363-.119-.675-.172-.955-.132l-1.896.27A.51.51 0 0 1 .15 7.17l2.382-2.386c.41-.41.947-.67 1.524-.734h.006l2.4-.238C9.005 1.55 11.087.582 12.623.208c.89-.217 1.59-.232 2.08-.188.244.023.435.06.57.093.067.017.12.033.16.045.184.06.279.13.351.295l.029.073a3.475 3.475 0 0 1 .157.721c.055.485.051 1.178-.159 2.065Zm-4.828 7.475.04-.04-.107 1.081a1.536 1.536 0 0 1-.44.913l-1.298 1.3.054-.38c.072-.506-.034-.993-.172-1.418a8.548 8.548 0 0 0-.164-.45c.738-.065 1.462-.38 2.087-1.006ZM5.205 5c-.625.626-.94 1.351-1.004 2.09a8.497 8.497 0 0 0-.45-.164c-.424-.138-.91-.244-1.416-.172l-.38.054 1.3-1.3c.245-.246.566-.401.91-.44l1.08-.107-.04.039Zm9.406-3.961c-.38-.034-.967-.027-1.746.163-1.558.38-3.917 1.496-6.937 4.521-.62.62-.799 1.34-.687 2.051.107.676.483 1.362 1.048 1.928.564.565 1.25.941 1.924 1.049.71.112 1.429-.067 2.048-.688 3.079-3.083 4.192-5.444 4.556-6.987.183-.771.18-1.345.138-1.713a2.835 2.835 0 0 0-.045-.283 3.078 3.078 0 0 0-.3-.041Z"/>
                <path d="M7.009 12.139a7.632 7.632 0 0 1-1.804-1.352A7.568 7.568 0 0 1 3.794 8.86c-1.102.992-1.965 5.054-1.839 5.18.125.126 3.936-.896 5.054-1.902Z"/>
            </svg>
            Departure
        </th>
        <th>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-rocket" viewBox="0 0 16 16">
                <path d="M8 8c.828 0 1.5-.895 1.5-2S8.828 4 8 4s-1.5.895-1.5 2S7.172 8 8 8Z"/>
                <path d="M11.953 8.81c-.195-3.388-.968-5.507-1.777-6.819C9.707 1.233 9.23.751 8.857.454a3.495 3.495 0 0 0-.463-.315A2.19 2.19 0 0 0 8.25.064.546.546 0 0 0 8 0a.549.549 0 0 0-.266.073 2.312 2.312 0 0 0-.142.08 3.67 3.67 0 0 0-.459.33c-.37.308-.844.803-1.31 1.57-.805 1.322-1.577 3.433-1.774 6.756l-1.497 1.826-.004.005A2.5 2.5 0 0 0 2 12.202V15.5a.5.5 0 0 0 .9.3l1.125-1.5c.166-.222.42-.4.752-.57.214-.108.414-.192.625-.281l.198-.084c.7.428 1.55.635 2.4.635.85 0 1.7-.207 2.4-.635.067.03.132.056.196.083.213.09.413.174.627.282.332.17.586.348.752.57l1.125 1.5a.5.5 0 0 0 .9-.3v-3.298a2.5 2.5 0 0 0-.548-1.562l-1.499-1.83ZM12 10.445v.055c0 .866-.284 1.585-.75 2.14.146.064.292.13.425.199.39.197.8.46 1.1.86L13 14v-1.798a1.5 1.5 0 0 0-.327-.935L12 10.445ZM4.75 12.64C4.284 12.085 4 11.366 4 10.5v-.054l-.673.82a1.5 1.5 0 0 0-.327.936V14l.225-.3c.3-.4.71-.664 1.1-.861.133-.068.279-.135.425-.199ZM8.009 1.073c.063.04.14.094.226.163.284.226.683.621 1.09 1.28C10.137 3.836 11 6.237 11 10.5c0 .858-.374 1.48-.943 1.893C9.517 12.786 8.781 13 8 13c-.781 0-1.517-.214-2.057-.607C5.373 11.979 5 11.358 5 10.5c0-4.182.86-6.586 1.677-7.928.409-.67.81-1.082 1.096-1.32.09-.076.17-.135.236-.18Z"/>
                <path d="M9.479 14.361c-.48.093-.98.139-1.479.139-.5 0-.999-.046-1.479-.139L7.6 15.8a.5.5 0 0 0 .8 0l1.079-1.439Z"/>
            </svg>
            Arriving
        </th>
        <th>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-check" viewBox="0 0 16 16">
                <path d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
            </svg>
            Data
        </th>
        <th>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-alarm" viewBox="0 0 16 16">
                <path d="M8.5 5.5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9V5.5z"/>
                <path d="M6.5 0a.5.5 0 0 0 0 1H7v1.07a7.001 7.001 0 0 0-3.273 12.474l-.602.602a.5.5 0 0 0 .707.708l.746-.746A6.97 6.97 0 0 0 8 16a6.97 6.97 0 0 0 3.422-.892l.746.746a.5.5 0 0 0 .707-.708l-.601-.602A7.001 7.001 0 0 0 9 2.07V1h.5a.5.5 0 0 0 0-1h-3zm1.038 3.018a6.093 6.093 0 0 1 .924 0 6 6 0 1 1-.924 0zM0 3.5c0 .753.333 1.429.86 1.887A8.035 8.035 0 0 1 4.387 1.86 2.5 2.5 0 0 0 0 3.5zM13.5 1c-.753 0-1.429.333-1.887.86a8.035 8.035 0 0 1 3.527 3.527A2.5 2.5 0 0 0 13.5 1z"/>
            </svg>
            Time
        </th>
        <th>Actions</th>
    </tr>
    </thead>
    {% for viagem in viagens %}
        <tr>
            <td>{{ viagem.id }}</td>
            <td>{{ viagem.departure }}</td>
            <td>{{ viagem.arriving }}</td>
            <td>{{ viagem.data }}</td>
            <td>{{ viagem.time }}</td>
            <td><a href="{% url 'detail_travel' viagem.id %}"><span class="badge text-bg-primary">Travel Detail</span><a/></td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="4">No trips found for your search criteria.</td>
        </tr>
    {% endfor %}
</table>
{% else %}
<p>No trips found for your search criteria.</p>
{% endif %}
<br>
<a class="btn btn-primary" href="{% url 'search_trips' %}">New search</a>
</div>
{% endblock %}

travel/templates/search_trips.html
{% extends "base.html" %}
{% block 'title' %}Search Trips{% endblock %}

{% block 'body' %}
<div class="my-3 p-3 bg-body rounded shadow-sm">
<h1>
    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
    </svg>
    Search Trips
</h1>
<hr>
<!--BUSCADOR COMEÇA AQUI-->
<form method="post" action="{% url 'search_trips' %}">{% csrf_token %}
<div class="row g-2">
    <div class="col-md-4">
        <div class="form-floating">
            <select class="form-select" name="departure" required id="id_departure" aria-label="Floating label select example">
              <option selected>Open this select menu...</option>
              <option value="1">Mercury</option>
              <option value="2">Venus</option>
              <option value="3">Earth</option>
              <option value="4">Mars</option>
              <option value="5">Jupiter</option>
              <option value="6">Saturn</option>
              <option value="7">Uranus</option>
              <option value="8">Neptune</option>
              <option value="9">Pluto</option>
            </select>
            <label for="id_departure">Departure (Planet)</label>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-floating">
            <select class="form-select" name="arriving" required id="id_arriving" aria-label="Floating label select example">
              <option selected>Open this select menu...</option>
              <option value="1">Mercury</option>
              <option value="2">Venus</option>
              <option value="3">Earth</option>
              <option value="4">Mars</option>
              <option value="5">Jupiter</option>
              <option value="6">Saturn</option>
              <option value="7">Uranus</option>
              <option value="8">Neptune</option>
              <option value="9">Pluto</option>
            </select>
            <label for="id_arriving">Arriving (Planet)</label>
        </div>
    </div>

    <div class="col-md-2">
        <div class="form-floating">
        <select class="form-select" name="data" required id="id_data">
            <option value="2023-10-09">
            2023-10-09
            </option>
        </select>
        <label for="id_data">Travel Date</label>            
        </div>
    </div>
    <div class="col-md-2">
        <div class="d-grid gap-2">
        <button type="submit" class="btn btn-lg btn-primary">Search</button>
        </div>
    </div>
    </div>
    <!--BUSCADOR TERMINA AQUI-->
</form>
<br>
<br>
<a href="{% url 'list_planets' %}" class="btn btn-secondary">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-globe-americas" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0ZM2.04 4.326c.325 1.329 2.532 2.54 3.717 3.19.48.263.793.434.743.484-.08.08-.162.158-.242.234-.416.396-.787.749-.758 1.266.035.634.618.824 1.214 1.017.577.188 1.168.38 1.286.983.082.417-.075.988-.22 1.52-.215.782-.406 1.48.22 1.48 1.5-.5 3.798-3.186 4-5 .138-1.243-2-2-3.5-2.5-.478-.16-.755.081-.99.284-.172.15-.322.279-.51.216-.445-.148-2.5-2-1.5-2.5.78-.39.952-.171 1.227.182.078.099.163.208.273.318.609.304.662-.132.723-.633.039-.322.081-.671.277-.867.434-.434 1.265-.791 2.028-1.12.712-.306 1.365-.587 1.579-.88A7 7 0 1 1 2.04 4.327Z"/>
    </svg>
    List of Available Planets
</a>
<a href="{% url 'search_earth_trips' %}" class="btn btn-secondary">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-globe-americas" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0ZM2.04 4.326c.325 1.329 2.532 2.54 3.717 3.19.48.263.793.434.743.484-.08.08-.162.158-.242.234-.416.396-.787.749-.758 1.266.035.634.618.824 1.214 1.017.577.188 1.168.38 1.286.983.082.417-.075.988-.22 1.52-.215.782-.406 1.48.22 1.48 1.5-.5 3.798-3.186 4-5 .138-1.243-2-2-3.5-2.5-.478-.16-.755.081-.99.284-.172.15-.322.279-.51.216-.445-.148-2.5-2-1.5-2.5.78-.39.952-.171 1.227.182.078.099.163.208.273.318.609.304.662-.132.723-.633.039-.322.081-.671.277-.867.434-.434 1.265-.791 2.028-1.12.712-.306 1.365-.587 1.579-.88A7 7 0 1 1 2.04 4.327Z"/>
    </svg>
    Trips Departure Earth
</a>
</div>
{% endblock %}